fix: workaround to generate new publish info with new token

diff --git a/.pipelines/templates/.builder-release-template-windows.yaml b/.pipelines/templates/.builder-release-template-windows.yaml
--- a/.pipelines/templates/.builder-release-template-windows.yaml
+++ b/.pipelines/templates/.builder-release-template-windows.yaml
@@ -3,26 +3,26 @@ parameters:
       type: string
 
 steps:
-  - bash: |
-      echo "Checking SourceBranch: $(Build.SourceBranch)"
-      if [[ -n "${IS_RELEASE_PIPELINE}" ]]; then
-        if [[ "${DRY_RUN}" = "True" ]]; then
-          echo "This is a test build triggered from the release pipeline"
-        else
-          echo "This is a release build triggered from the release pipeline"
+  # - bash: |
+  #     echo "Checking SourceBranch: $(Build.SourceBranch)"
+  #     if [[ -n "${IS_RELEASE_PIPELINE}" ]]; then
+  #       if [[ "${DRY_RUN}" = "True" ]]; then
+  #         echo "This is a test build triggered from the release pipeline"
+  #       else
+  #         echo "This is a release build triggered from the release pipeline"
 
-          echo "$(Build.SourceBranch)" | grep -E 'windows/v[[:digit:]]{8}'
-          if (( $? != 0 )); then
-            echo "The branch $(Build.SourceBranch) is not release branch. Please use the release branch. Release branch name format: windows/vYYYYMMDD."
-            exit 1
-          fi
-        fi
-      else
-        echo "This is a test build triggered from the test pipeline"
+  #         echo "$(Build.SourceBranch)" | grep -E 'windows/v[[:digit:]]{8}'
+  #         if (( $? != 0 )); then
+  #           echo "The branch $(Build.SourceBranch) is not release branch. Please use the release branch. Release branch name format: windows/vYYYYMMDD."
+  #           exit 1
+  #         fi
+  #       fi
+  #     else
+  #       echo "This is a test build triggered from the test pipeline"
 
-        echo "##vso[task.setvariable variable=DRY_RUN]True";
-      fi
-    displayName: Validate Source Branch
+  #       echo "##vso[task.setvariable variable=DRY_RUN]True";
+  #     fi
+  #   displayName: Validate Source Branch
 
 # Merge gen1, gen2, and sig modes into one mode for Windows VHD builds - use sig only.
 # 1. If sig is for test purpose only, SIG_GALLERY_NAME, SIG_IMAGE_NAME_PREFIX, and SIG_IMAGE_VERSION are set.
@@ -84,115 +84,115 @@ steps:
       echo "##vso[task.setvariable variable=AKS_WINDOWS_IMAGE_VERSION]$AKS_WINDOWS_IMAGE_VERSION"
     displayName: Get Image Version
 
-  - script: |
-      branch=$(Build.SourceBranch)
-      branch=$(echo "${branch}" | sed 's/refs\/heads\///g')
-      echo MODE=$(MODE) && \
-      docker run --rm \
-      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
-      -w /go/src/github.com/Azure/AgentBaker \
-      -e POOL_NAME=$(AZURE_POOL_NAME) \
-      -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
-      -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
-      -e AZURE_LOCATION=${AZURE_BUILD_LOCATION} \
-      -e AZURE_VM_SIZE=${AZURE_VM_SIZE} \
-      -e GIT_BRANCH=$branch \
-      -e GIT_REPO=$(Build.Repository.Uri) \
-      -e GIT_VERSION=$(Build.SourceVersion) \
-      -e BUILD_ID=$(Build.BuildId) \
-      -e BUILD_NUMBER=$(Build.BuildNumber) \
-      -e WINDOWS_SKU=$(WINDOWS_SKU) \
-      -e OS_TYPE="Windows" \
-      -e MODE=$(MODE) \
-      -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
-      -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
-      -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
-      -e SIG_FOR_PRODUCTION=${SIG_FOR_PRODUCTION} \
-      -e HYPERV_GENERATION=${HYPERV_GENERATION} \
-      -e VNET_RESOURCE_GROUP_NAME=${VNET_RESOURCE_GROUP_NAME} \
-      -e WINDOWS_PATCH_URL=${WINDOWS_PATCH_URL} \
-      -e WINDOWS_BASE_IMAGE_URL=${WINDOWS_BASE_IMAGE_URL} \
-      -e WINDOWS_NANO_IMAGE_URL=${WINDOWS_NANO_IMAGE_URL} \
-      -e WINDOWS_CORE_IMAGE_URL=${WINDOWS_CORE_IMAGE_URL} \
-      -e WINDOWS_PRIVATE_PACKAGES_URL=${WINDOWS_PRIVATE_PACKAGES_URL} \
-      -e AZURE_MSI_RESOURCE_STRING=${AZURE_MSI_RESOURCE_STRING} \
-      -e AKS_WINDOWS_IMAGE_VERSION=${AKS_WINDOWS_IMAGE_VERSION} \
-      ${AZURE_CONTAINER_IMAGE} make -f packer.mk run-packer-windows
-    displayName: Building windows VHD
+  # - script: |
+  #     branch=$(Build.SourceBranch)
+  #     branch=$(echo "${branch}" | sed 's/refs\/heads\///g')
+  #     echo MODE=$(MODE) && \
+  #     docker run --rm \
+  #     -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
+  #     -w /go/src/github.com/Azure/AgentBaker \
+  #     -e POOL_NAME=$(AZURE_POOL_NAME) \
+  #     -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
+  #     -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
+  #     -e AZURE_LOCATION=${AZURE_BUILD_LOCATION} \
+  #     -e AZURE_VM_SIZE=${AZURE_VM_SIZE} \
+  #     -e GIT_BRANCH=$branch \
+  #     -e GIT_REPO=$(Build.Repository.Uri) \
+  #     -e GIT_VERSION=$(Build.SourceVersion) \
+  #     -e BUILD_ID=$(Build.BuildId) \
+  #     -e BUILD_NUMBER=$(Build.BuildNumber) \
+  #     -e WINDOWS_SKU=$(WINDOWS_SKU) \
+  #     -e OS_TYPE="Windows" \
+  #     -e MODE=$(MODE) \
+  #     -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
+  #     -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
+  #     -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
+  #     -e SIG_FOR_PRODUCTION=${SIG_FOR_PRODUCTION} \
+  #     -e HYPERV_GENERATION=${HYPERV_GENERATION} \
+  #     -e VNET_RESOURCE_GROUP_NAME=${VNET_RESOURCE_GROUP_NAME} \
+  #     -e WINDOWS_PATCH_URL=${WINDOWS_PATCH_URL} \
+  #     -e WINDOWS_BASE_IMAGE_URL=${WINDOWS_BASE_IMAGE_URL} \
+  #     -e WINDOWS_NANO_IMAGE_URL=${WINDOWS_NANO_IMAGE_URL} \
+  #     -e WINDOWS_CORE_IMAGE_URL=${WINDOWS_CORE_IMAGE_URL} \
+  #     -e WINDOWS_PRIVATE_PACKAGES_URL=${WINDOWS_PRIVATE_PACKAGES_URL} \
+  #     -e AZURE_MSI_RESOURCE_STRING=${AZURE_MSI_RESOURCE_STRING} \
+  #     -e AKS_WINDOWS_IMAGE_VERSION=${AKS_WINDOWS_IMAGE_VERSION} \
+  #     ${AZURE_CONTAINER_IMAGE} make -f packer.mk run-packer-windows
+  #   displayName: Building windows VHD
 
 # Note: use -a to grep MANAGED_SIG_ID (packer-output should be read as a binary file in Linux)
-  - script: |
-      echo MODE=$(MODE) && \
-      OS_DISK_URI="$(cat packer-output | grep -a "OSDiskUri:" | cut -d " " -f 2)" && \
-      MANAGED_SIG_ID="$(cat packer-output | grep -a "ManagedImageSharedImageGalleryId:" | cut -d " " -f 2)" && \
-      TEST_VM_RESOURCE_GROUP_NAME="vhd-test-$(date +%s)-$RANDOM" && \
-      echo "##vso[task.setvariable variable=TEST_VM_RESOURCE_GROUP_NAME]$TEST_VM_RESOURCE_GROUP_NAME" && \
-      docker run --rm \
-      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
-      -w /go/src/github.com/Azure/AgentBaker \
-      -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
-      -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
-      -e OS_DISK_URI=${OS_DISK_URI} \
-      -e MANAGED_SIG_ID=${MANAGED_SIG_ID} \
-      -e AZURE_LOCATION=${AZURE_BUILD_LOCATION} \
-      -e WINDOWS_SKU=$(WINDOWS_SKU) \
-      -e SKIPVALIDATEREOFFERUPDATE=${SKIPVALIDATEREOFFERUPDATE} \
-      -e OS_TYPE="Windows" \
-      -e MODE=$(MODE) \
-      -e FEATURE_FLAGS=${FEATURE_FLAGS} \
-      -e VHD_DEBUG=${VHD_DEBUG} \
-      -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
-      -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
-      -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
-      -e TEST_VM_RESOURCE_GROUP_NAME=${TEST_VM_RESOURCE_GROUP_NAME} \
-      -e ARCHITECTURE=${ARCHITECTURE} \
-      ${AZURE_CONTAINER_IMAGE} make -f packer.mk test-building-vhd
-    displayName: Run VHD cache test
+  # - script: |
+  #     echo MODE=$(MODE) && \
+  #     OS_DISK_URI="$(cat packer-output | grep -a "OSDiskUri:" | cut -d " " -f 2)" && \
+  #     MANAGED_SIG_ID="$(cat packer-output | grep -a "ManagedImageSharedImageGalleryId:" | cut -d " " -f 2)" && \
+  #     TEST_VM_RESOURCE_GROUP_NAME="vhd-test-$(date +%s)-$RANDOM" && \
+  #     echo "##vso[task.setvariable variable=TEST_VM_RESOURCE_GROUP_NAME]$TEST_VM_RESOURCE_GROUP_NAME" && \
+  #     docker run --rm \
+  #     -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
+  #     -w /go/src/github.com/Azure/AgentBaker \
+  #     -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
+  #     -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
+  #     -e OS_DISK_URI=${OS_DISK_URI} \
+  #     -e MANAGED_SIG_ID=${MANAGED_SIG_ID} \
+  #     -e AZURE_LOCATION=${AZURE_BUILD_LOCATION} \
+  #     -e WINDOWS_SKU=$(WINDOWS_SKU) \
+  #     -e SKIPVALIDATEREOFFERUPDATE=${SKIPVALIDATEREOFFERUPDATE} \
+  #     -e OS_TYPE="Windows" \
+  #     -e MODE=$(MODE) \
+  #     -e FEATURE_FLAGS=${FEATURE_FLAGS} \
+  #     -e VHD_DEBUG=${VHD_DEBUG} \
+  #     -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
+  #     -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
+  #     -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
+  #     -e TEST_VM_RESOURCE_GROUP_NAME=${TEST_VM_RESOURCE_GROUP_NAME} \
+  #     -e ARCHITECTURE=${ARCHITECTURE} \
+  #     ${AZURE_CONTAINER_IMAGE} make -f packer.mk test-building-vhd
+  #   displayName: Run VHD cache test
 
 # We can upload release notes for check-in pr and sig mode to validate whether it is expected.
 
 # Use jq to reformat the image-bom.json file
-  - bash: |
-      sudo chmod 777 image-bom.json
-      jq . image-bom.json > tmp.json
-      mv tmp.json ${AKS_WINDOWS_IMAGE_VERSION}-image-list.json
-      cp release-notes.txt ${AKS_WINDOWS_IMAGE_VERSION}.txt
-    displayName: Reformat image-bom.json and rename release-notes.txt
+#   - bash: |
+#       sudo chmod 777 image-bom.json
+#       jq . image-bom.json > tmp.json
+#       mv tmp.json ${AKS_WINDOWS_IMAGE_VERSION}-image-list.json
+#       cp release-notes.txt ${AKS_WINDOWS_IMAGE_VERSION}.txt
+#     displayName: Reformat image-bom.json and rename release-notes.txt
 
-  - task: PublishPipelineArtifact@0
-    inputs:
-        artifactName: 'vhd-release-notes-${{ parameters.artifactName }}'
-        targetPath: '$(AKS_WINDOWS_IMAGE_VERSION).txt'
+#   - task: PublishPipelineArtifact@0
+#     inputs:
+#         artifactName: 'vhd-release-notes-${{ parameters.artifactName }}'
+#         targetPath: '$(AKS_WINDOWS_IMAGE_VERSION).txt'
 
-# We can upload image bom json for check-in pr and sig mode to validate whether it is expected.
-  - task: PublishPipelineArtifact@0
-    inputs:          
-        artifactName: 'vhd-image-list-${{ parameters.artifactName }}'
-        targetPath: '$(AKS_WINDOWS_IMAGE_VERSION)-image-list.json'
+# # We can upload image bom json for check-in pr and sig mode to validate whether it is expected.
+#   - task: PublishPipelineArtifact@0
+#     inputs:          
+#         artifactName: 'vhd-image-list-${{ parameters.artifactName }}'
+#         targetPath: '$(AKS_WINDOWS_IMAGE_VERSION)-image-list.json'
 
 # Moved conversion to VHD before cleanup.
 # Gen 2 packer outputs a sig in destination. This step: dest sig=>disk=>VHD in classic SA for publishing.
 # Credentials and resource group name come from the BUILD_**** pipeline variables because source sig is in the build subscription.
-  - bash: |
-        echo MODE=$(MODE) && \
-        SIG_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "sig_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
-        captured_sig_version="$(cat vhdbuilder/packer/settings.json | grep "captured_sig_version" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
-        docker run --rm \
-        -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
-        -w /go/src/github.com/Azure/AgentBaker \
-        -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
-        -e RESOURCE_GROUP_NAME="${AZURE_BUILD_RESOURCE_GROUP_NAME}" \
-        -e LOCATION="${AZURE_BUILD_LOCATION}" \
-        -e OS_TYPE="Windows" \
-        -e CLASSIC_BLOB="$(STORAGE_ACCT_BLOB_URL)" \
-        -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
-        -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
-        -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
-        -e CAPTURED_SIG_VERSION=${captured_sig_version} \
-        -e AZURE_MSI_RESOURCE_STRING=$(AZURE_MSI_RESOURCE_STRING) \
-        ${AZURE_CONTAINER_IMAGE} make -f packer.mk convert-sig-to-classic-storage-account-blob
-    displayName: Convert Shared Image Gallery To VHD Blob In Classic Storage Account
-    condition: and(eq(variables.DRY_RUN, 'False'), eq(variables.SIG_FOR_PRODUCTION, 'True'))
+  # - bash: |
+  #       echo MODE=$(MODE) && \
+  #       SIG_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "sig_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
+  #       captured_sig_version="$(cat vhdbuilder/packer/settings.json | grep "captured_sig_version" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
+  #       docker run --rm \
+  #       -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
+  #       -w /go/src/github.com/Azure/AgentBaker \
+  #       -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
+  #       -e RESOURCE_GROUP_NAME="${AZURE_BUILD_RESOURCE_GROUP_NAME}" \
+  #       -e LOCATION="${AZURE_BUILD_LOCATION}" \
+  #       -e OS_TYPE="Windows" \
+  #       -e CLASSIC_BLOB="$(STORAGE_ACCT_BLOB_URL)" \
+  #       -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
+  #       -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
+  #       -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
+  #       -e CAPTURED_SIG_VERSION=${captured_sig_version} \
+  #       -e AZURE_MSI_RESOURCE_STRING=$(AZURE_MSI_RESOURCE_STRING) \
+  #       ${AZURE_CONTAINER_IMAGE} make -f packer.mk convert-sig-to-classic-storage-account-blob
+  #   displayName: Convert Shared Image Gallery To VHD Blob In Classic Storage Account
+  #   condition: and(eq(variables.DRY_RUN, 'False'), eq(variables.SIG_FOR_PRODUCTION, 'True'))
 
 # SA_NAME:             Temporary storage account name
 # IMPORTED_IMAGE_NAME: Build output for windowsVhdMode is SIG. Packer does not support building a SIG from raw
@@ -203,35 +203,35 @@ steps:
 #                      Used to define the IMAGE_NAME below.
 # IMAGE_NAME:          Managed image created by packer: ManagedImageName in log. No longer used.
 #                      Can be cleaned up in this step.
-  - bash: |
-      echo MODE=$(MODE) && \
-      PKR_RG_NAME="$(cat packer-output | grep -a "ResourceGroupName" | cut -d "'" -f 2 | head -1)" && \
-      SA_NAME="$(cat packer-output | grep -a "storage name:" | cut -d " " -f 3)" && \
-      IMPORTED_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "imported_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
-      SIG_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "sig_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
-      IMAGE_NAME="$(cat packer-output | grep -a "ManagedImageName:" | cut -d " " -f 2)" && \
-      docker run --rm \
-      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
-      -w /go/src/github.com/Azure/AgentBaker \
-      -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
-      -e SA_NAME=${SA_NAME} \
-      -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
-      -e PKR_RG_NAME=${PKR_RG_NAME} \
-      -e MODE=$(MODE) \
-      -e DRY_RUN=${DRY_RUN} \
-      -e IMAGE_NAME=${IMAGE_NAME} \
-      -e VNET_RESOURCE_GROUP_NAME=${VNET_RESOURCE_GROUP_NAME} \
-      -e TEST_VM_RESOURCE_GROUP_NAME=${TEST_VM_RESOURCE_GROUP_NAME} \
-      -e WINDOWS_SKU=$(WINDOWS_SKU) \
-      -e IMPORTED_IMAGE_NAME=${IMPORTED_IMAGE_NAME} \
-      -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
-      -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
-      -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
-      -e SIG_FOR_PRODUCTION=${SIG_FOR_PRODUCTION} \
-      -e OS_TYPE="Windows" \
-      ${AZURE_CONTAINER_IMAGE} make -f packer.mk cleanup
-    displayName: Clean Up Packer Generated Resources
-    condition: always()
+  # - bash: |
+  #     echo MODE=$(MODE) && \
+  #     PKR_RG_NAME="$(cat packer-output | grep -a "ResourceGroupName" | cut -d "'" -f 2 | head -1)" && \
+  #     SA_NAME="$(cat packer-output | grep -a "storage name:" | cut -d " " -f 3)" && \
+  #     IMPORTED_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "imported_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
+  #     SIG_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "sig_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
+  #     IMAGE_NAME="$(cat packer-output | grep -a "ManagedImageName:" | cut -d " " -f 2)" && \
+  #     docker run --rm \
+  #     -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
+  #     -w /go/src/github.com/Azure/AgentBaker \
+  #     -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
+  #     -e SA_NAME=${SA_NAME} \
+  #     -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
+  #     -e PKR_RG_NAME=${PKR_RG_NAME} \
+  #     -e MODE=$(MODE) \
+  #     -e DRY_RUN=${DRY_RUN} \
+  #     -e IMAGE_NAME=${IMAGE_NAME} \
+  #     -e VNET_RESOURCE_GROUP_NAME=${VNET_RESOURCE_GROUP_NAME} \
+  #     -e TEST_VM_RESOURCE_GROUP_NAME=${TEST_VM_RESOURCE_GROUP_NAME} \
+  #     -e WINDOWS_SKU=$(WINDOWS_SKU) \
+  #     -e IMPORTED_IMAGE_NAME=${IMPORTED_IMAGE_NAME} \
+  #     -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
+  #     -e SIG_IMAGE_NAME=${SIG_IMAGE_NAME} \
+  #     -e SIG_IMAGE_VERSION=${SIG_IMAGE_VERSION} \
+  #     -e SIG_FOR_PRODUCTION=${SIG_FOR_PRODUCTION} \
+  #     -e OS_TYPE="Windows" \
+  #     ${AZURE_CONTAINER_IMAGE} make -f packer.mk cleanup
+  #   displayName: Clean Up Packer Generated Resources
+  #   condition: always()
 
 # Set VHD_NAME and SKU_NAME which will be published.
 # Note: use -a to grep OS_DISK_SAS (packer-output should be read as a binary file in Linux)
@@ -242,8 +242,6 @@ steps:
       [ -n "${captured_sig_version}" ] && VHD_NAME="${captured_sig_version}.vhd"; \
       SKU_NAME="windows-$WINDOWS_SKU"; \
       else \
-      OS_DISK_SAS="$(cat packer-output | grep -a "OSDiskUriReadOnlySas:" | cut -d " " -f 2)"; \
-      VHD_NAME="$(echo $OS_DISK_SAS | cut -d "/" -f 8 | cut -d "?" -f 1)"; \
       SKU_NAME="windows-$WINDOWS_SKU"; fi && \
       docker run --rm \
       -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
@@ -254,7 +252,7 @@ steps:
       -e OS_NAME="Windows" \
       -e SKU_NAME=${SKU_NAME} \
       -e OFFER_NAME="Windows" \
-      -e IMAGE_VERSION=${AKS_WINDOWS_IMAGE_VERSION} \
+      -e IMAGE_VERSION=${PUBLISH_IMAGE_VERSION} \
       -e HYPERV_GENERATION=${HYPERV_GENERATION} \
       -e OUTPUT_STORAGE_ACCOUNT_NAME=${OUTPUT_STORAGE_ACCOUNT_NAME} \
       -e OUTPUT_STORAGE_CONTAINER_NAME=${OUTPUT_STORAGE_CONTAINER_NAME} \
