chore: generate installation token for automation

diff --git a/.pipelines/templates/.generate-github-token.yaml b/.pipelines/templates/.generate-github-token.yaml
--- a/.pipelines/templates/.generate-github-token.yaml
+++ b/.pipelines/templates/.generate-github-token.yaml
@@ -1,25 +1,64 @@
-parameters:
-- name: VHD_BUILD_ID
-  type: string
-- name: IMAGE_VERSION_OVERRIDE
-  type: string
-  default: ""
-
 steps:
 - bash: |
-    if [ -n "$IMAGE_VERSION_OVERRIDE" ]; then
-      echo "IMAGE_VERSION_OVERRIDE is set to $IMAGE_VERSION_OVERRIDE"
-      echo "##vso[task.setvariable variable=IMAGE_VERSION]$IMAGE_VERSION_OVERRIDE"
-      exit 0
+    set -euo pipefail
+
+    if [ -z "$PRIVATE_KEY" ]; then
+      echo "PRIVATE_KEY must be supplied to generate installation token for aks-node-sig-release-assistant"
+      exit 1
     fi
-  
-    source vhdbuilder/scripts/automate_generate_version.sh
-    echo "setting image version to $GENERATED_IMAGE_VERSION"
-    echo "##vso[task.setvariable variable=IMAGE_VERSION]$GENERATED_IMAGE_VERSION"
+    if [ -z "$CLIENT_ID" ]; then
+      echo "CLIENT_ID must be supplied to generate installation token for aks-node-sig-release-assistant"
+      exit 1
+    fi
+
+    now=$(date +%s)
+    iat=$((${now} - 60)) # issues 60 seconds in the past
+    exp=$((${now} + 600)) # expires 10 minutes in the future
+
+    b64enc() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }
+
+    header_json='{
+        "typ":"JWT",
+        "alg":"RS256"
+    }'
+    # encode the JWT header
+    header=$(echo -n "${header_json}" | b64enc)
+
+    payload_json="{
+        \"iat\":${iat},
+        \"exp\":${exp},
+        \"iss\":\"${CLIENT_ID}\"
+    }"
+    # encode the JWT payload
+    payload=$(echo -n "${payload_json}" | b64enc)
+
+    # create the JWT signature
+    header_payload="${header}"."${payload}"
+    signature=$(
+        openssl dgst -sha256 -sign <(echo -n "${PRIVATE_KEY}") \
+        <(echo -n "${header_payload}") | b64enc
+    )
+
+    # create the JWT
+    jwt="${header_payload}"."${signature}"
+
+    # get the installation token request URL
+    installation_token_url=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $jwt" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/app/installations | jq -r '.[0].access_tokens_url')
+    if [ -z "$installation_token_url" ] || [ "$installation_token_url" == "null" ]; then
+      echo "unable to get installation token URL"
+      exit 1
+    fi
+
+    # get the installation token
+    token=$(curl -X POST -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $jwt" -H "X-GitHub-Api-Version: 2022-11-28" "$installation_token_url" | jq -r '.token')
+    if [ -z "$token" ] || [ "$token" == "null" ]; then
+      echo "unable to get installation token"
+      exit 1
+    fi
+    
+    echo "generated installation token for aks-node-sig-release-assistant"
+    echo "##vso[task.setvariable variable=GITHUB_TOKEN;issecret=true]$token"
   env:
-    VHD_BUILD_ID: ${{ parameters.VHD_BUILD_ID }}
-  displayName: 'Set image version'
-- bash: |
-    echo "removing dangling publishing-info.json artifacts..."
-    rm -f *vhd-publishing-info.json
-  displayName: 'Cleanup publishing-info.json artifacts'
+    PRIVATE_KEY: $(aks-node-sig-release-assistant-private-key)
+    CLIENT_ID: $(aks-node-sig-release-assistant-client-id)
+  displayName: Generate GitHub token
