bring back step

diff --git a/.pipelines/templates/e2e-template.yaml b/.pipelines/templates/e2e-template.yaml
--- a/.pipelines/templates/e2e-template.yaml
+++ b/.pipelines/templates/e2e-template.yaml
@@ -18,7 +18,6 @@ jobs:
       - bash: |
           set -ex
           LOGGING_DIR="scenario-logs-$(date +%s)"
-          mkdir -p "$(System.DefaultWorkingDirectory)/e2e/$(LOGGING_DIR)"
           echo "setting logging dir to $LOGGING_DIR"
           echo "##vso[task.setvariable variable=LOGGING_DIR]$LOGGING_DIR"
         displayName: Set logging directory
@@ -45,6 +44,12 @@ jobs:
         env:
           VHD_BUILD_ID: $(VHD_BUILD_ID)
           LOGGING_DIR: $(LOGGING_DIR)
+      # Without this step next step may fail on successful run
+      - bash: |
+          set -ex
+          mkdir -p "$(System.DefaultWorkingDirectory)/e2e/$(LOGGING_DIR)"
+        condition: always()
+        displayName: Create folder for scenario logs
       - task: PublishTestResults@2
         displayName: Upload test results
         condition: succeededOrFailed()
