feat: add cve-query step

diff --git a/.pipelines/.vsts-vhd-builder.yaml b/.pipelines/.vsts-vhd-builder.yaml
--- a/.pipelines/.vsts-vhd-builder.yaml
+++ b/.pipelines/.vsts-vhd-builder.yaml
@@ -27,79 +27,104 @@ variables:
   - group: aks-vuln-to-kusto
 
 stages:
-  - stage: build
+  # - stage: build
+  #   jobs:
+  #   - job: build2204gen2containerd
+  #     timeoutInMinutes: 180
+  #     steps:
+  #       - bash: |
+  #           echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
+  #           echo '##vso[task.setvariable variable=OS_VERSION]22.04'
+  #           echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
+  #           echo '##vso[task.setvariable variable=IMG_OFFER]0001-com-ubuntu-server-jammy'
+  #           echo '##vso[task.setvariable variable=IMG_SKU]22_04-lts-gen2'
+  #           echo '##vso[task.setvariable variable=IMG_VERSION]latest'
+  #           echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
+  #           echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16ds_v5'
+  #           echo '##vso[task.setvariable variable=FEATURE_FLAGS]None'
+  #           echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
+  #           echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
+  #           echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
+  #           echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
+  #           echo '##vso[task.setvariable variable=SGX_INSTALL]True'
+  #         displayName: Setup Build Variables
+  #       - template: ./templates/.builder-release-template.yaml
+  #         parameters:
+  #           artifactName: 2204-gen2-containerd
+  #   - job: build1804gen2gpucontainerd
+  #     timeoutInMinutes: 180
+  #     steps:
+  #       - bash: |
+  #           echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
+  #           echo '##vso[task.setvariable variable=OS_VERSION]18.04'
+  #           echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
+  #           echo '##vso[task.setvariable variable=IMG_OFFER]UbuntuServer'
+  #           echo '##vso[task.setvariable variable=IMG_SKU]18_04-LTS-GEN2'
+  #           echo '##vso[task.setvariable variable=IMG_VERSION]latest'
+  #           echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
+  #           echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_NC4as_T4_v3'
+  #           echo '##vso[task.setvariable variable=FEATURE_FLAGS]fullgpudaemon'
+  #           echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
+  #           echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
+  #           echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
+  #           echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
+  #           echo '##vso[task.setvariable variable=SGX_INSTALL]True'
+  #         displayName: Setup Build Variables
+  #       - template: ./templates/.builder-release-template.yaml
+  #         parameters:
+  #           artifactName: 1804-gen2-gpu-containerd
+  #   - job: buildmarinerv2gen2
+  #     timeoutInMinutes: 180
+  #     steps:
+  #       - bash: |
+  #           echo '##vso[task.setvariable variable=OS_SKU]CBLMariner'
+  #           echo '##vso[task.setvariable variable=OS_VERSION]V2'
+  #           echo '##vso[task.setvariable variable=IMG_PUBLISHER]MicrosoftCBLMariner'
+  #           echo '##vso[task.setvariable variable=IMG_OFFER]cbl-mariner'
+  #           echo '##vso[task.setvariable variable=IMG_SKU]cbl-mariner-2-gen2'
+  #           echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
+  #           echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16ds_v5'
+  #           echo '##vso[task.setvariable variable=FEATURE_FLAGS]None'
+  #           echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
+  #           echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
+  #           echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
+  #           echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
+  #           echo '##vso[task.setvariable variable=SGX_INSTALL]True'
+  #           echo '##vso[task.setvariable variable=ENABLE_CGROUPV2]False'
+  #         displayName: Setup Build Variables
+  #       - template: ./templates/.builder-release-template.yaml
+  #         parameters:
+  #           artifactName: marinerv2-gen2
+  # - stage: e2e
+  #   condition: ne(variables.SKIP_E2E_TESTS, 'true')
+  #   variables:
+  #     VHD_BUILD_ID: $(Build.BuildId)
+  #     LOCATION: $(PACKER_BUILD_LOCATION)
+  #   jobs:
+  #     - template: ./templates/e2e-template.yaml
+  - stage: cve-query
     jobs:
-    - job: build2204gen2containerd
-      timeoutInMinutes: 180
-      steps:
-        - bash: |
-            echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
-            echo '##vso[task.setvariable variable=OS_VERSION]22.04'
-            echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
-            echo '##vso[task.setvariable variable=IMG_OFFER]0001-com-ubuntu-server-jammy'
-            echo '##vso[task.setvariable variable=IMG_SKU]22_04-lts-gen2'
-            echo '##vso[task.setvariable variable=IMG_VERSION]latest'
-            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
-            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16ds_v5'
-            echo '##vso[task.setvariable variable=FEATURE_FLAGS]None'
-            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
-            echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
-            echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
-            echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
-            echo '##vso[task.setvariable variable=SGX_INSTALL]True'
-          displayName: Setup Build Variables
-        - template: ./templates/.builder-release-template.yaml
-          parameters:
-            artifactName: 2204-gen2-containerd
-    - job: build1804gen2gpucontainerd
-      timeoutInMinutes: 180
-      steps:
-        - bash: |
-            echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
-            echo '##vso[task.setvariable variable=OS_VERSION]18.04'
-            echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
-            echo '##vso[task.setvariable variable=IMG_OFFER]UbuntuServer'
-            echo '##vso[task.setvariable variable=IMG_SKU]18_04-LTS-GEN2'
-            echo '##vso[task.setvariable variable=IMG_VERSION]latest'
-            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
-            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_NC4as_T4_v3'
-            echo '##vso[task.setvariable variable=FEATURE_FLAGS]fullgpudaemon'
-            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
-            echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
-            echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
-            echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
-            echo '##vso[task.setvariable variable=SGX_INSTALL]True'
-          displayName: Setup Build Variables
-        - template: ./templates/.builder-release-template.yaml
-          parameters:
-            artifactName: 1804-gen2-gpu-containerd
-    - job: buildmarinerv2gen2
-      timeoutInMinutes: 180
-      steps:
-        - bash: |
-            echo '##vso[task.setvariable variable=OS_SKU]CBLMariner'
-            echo '##vso[task.setvariable variable=OS_VERSION]V2'
-            echo '##vso[task.setvariable variable=IMG_PUBLISHER]MicrosoftCBLMariner'
-            echo '##vso[task.setvariable variable=IMG_OFFER]cbl-mariner'
-            echo '##vso[task.setvariable variable=IMG_SKU]cbl-mariner-2-gen2'
-            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
-            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16ds_v5'
-            echo '##vso[task.setvariable variable=FEATURE_FLAGS]None'
-            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
-            echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
-            echo '##vso[task.setvariable variable=ENABLE_FIPS]false'
-            echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
-            echo '##vso[task.setvariable variable=SGX_INSTALL]True'
-            echo '##vso[task.setvariable variable=ENABLE_CGROUPV2]False'
-          displayName: Setup Build Variables
-        - template: ./templates/.builder-release-template.yaml
-          parameters:
-            artifactName: marinerv2-gen2
-  - stage: e2e
-    condition: ne(variables.SKIP_E2E_TESTS, 'true')
-    variables:
-      VHD_BUILD_ID: $(Build.BuildId)
-      LOCATION: $(PACKER_BUILD_LOCATION)
-    jobs:
-      - template: ./templates/e2e-template.yaml
+      - job: cve-query
+        steps:
+          - bash: |
+              set -eux
+              az login --identity
+            displayName: Azure Login
+          - bash: |
+              arch="$(uname -m)"
+              if [ "${arch,,}" == "arm64" ] || [ "${arch,,}" == "aarch64" ]; then
+                  GO_ARCH="arm64"
+              elif [ "${arch,,}" == "x86_64" ]; then
+                  GO_ARCH="amd64"
+              else
+                  echo "invalid architecture ${arch,,}"
+                  exit 1
+              fi
 
+              az storage blob download --auth-mode login --account-name ${ACCOUNT_NAME} -c vuln-to-kusto \
+                --name ${MODULE_VERSION}/vuln-to-kusto-vhd_linux_${GO_ARCH} \
+                --file ./vuln-to-kusto-vhd
+              chmod a+x vuln-to-kusto-vhd
+            displayName: Download vuln-to-kusto binary
+
+          
